### ISSUE TITLE
How to send and receive a file?

### ISSUE THREAD

**Issue by davidUrr** [erayerdin/pyairmore#15]
It is possible to take a file and send via SMS

Thank you

**Comment by erayerdin** [comment]
I do not understand if this is a question or not, but sending and receiving files with _pure SMS_ is impossible. I, of course, do not know if Google or Apple has found a workaround for this (like, sending the file over their servers). If this ever is the case, I do not think Airmore team (I am not one of them) has implemented such a feature, especially considering that Airmore on Android seldom receives updates.

**Simple Answer:** No, that is not possible.
