### ISSUE TITLE
Not able to send SMS

### ISSUE THREAD

**Issue by kRiShNa-429407** [erayerdin/pyairmore#28]
It shows two error messages. i attached the images for the same.
I also done battery , permission all the things you mentioned but not working.

![Screenshot 2024-05-18 121402](https://github.com/erayerdin/pyairmore/assets/131583096/49fa28e5-aadd-4302-8ac2-ff2a4f168ac5)
![Screenshot 2024-05-18 121411](https://github.com/erayerdin/pyairmore/assets/131583096/7e49d9f9-cf2f-462e-b5ab-46f95211619b)

**Comment by erayerdin** [comment]
As I've mentioned in the README, the project is stale (last commit is 6 years ago). During this phase, Airmore might've changed its internals, so it might not work as expected.

Just in case anyone is interested sending a PR or just to let others know, I will keep this issue open.

**Comment by kRiShNa-429407** [comment]
Okk
Thank you for informing
